### ISSUE TITLE
No icon after installation

### ISSUE THREAD

**Issue by Boia11** [OpenMediaVault-Plugin-Developers/openmediavault-remotedesktop#2]
Hi, after installation of plugin remote-desktop on OMV the remote interface don't see the icon.
It fix itself after install of epiphany-browser using command: `apt-get install epiphany-browser`

**Comment by ryecoaaron** [comment]
I didn't add a dependency on any browser because some people may want a different browser or no browser at all.

**Comment by Boia11** [comment]
But the question are icons 😇, I see that the dependence of this browser include the  GNOME-icons


_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Boia11** [comment]
@ryecoaaron  read that --> https://bbs.archlinux.org/viewtopic.php?id=67318
This is a problem of no show icon.....solve with simple : `apt-get install gnome-icon-theme` ;)
Add this as dependency and try

**Comment by ryecoaaron** [comment]
When I created the plugin, I wanted to install the least amount of packages in order to get remote desktop to function.  That "solution" may be a simple apt-get or dependency of the plugin but it adds 30 more packages.
